hw06 done
dmitriye/golang-homeworks pull request #6
Opened 2021-09-05 15:28 UTC by dmitriye

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2021-09-11 14:41 UTC, kulti requested changes
Дмитрий, хорошее решение и тесты 👍 

Есть один недочет в цепочке стейджей. Из-за него может нестабильно работать.

2021-09-11 14:41 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	return out
Посмотрите внимательно на оборачивание с помощью done. Получилась такая последовательность стейджей:
in -> done -> done -> stage_1 -> done -> ... -> stage_n -> out

В начале дублируется done-стейдж. В конце же его наоборот не хватает, чтобы разорвать цепочку. Если последний стейдж будет «долго» работать, то пайплайн будет долго останавливаться. Тесты это обычно отлавливают при многократном запуске.

2021-09-11 14:41 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Тут может произойти так, что из out никто не читает. Т.е. горутина зависнет навсегда. В этом ДЗ нет требования, чтобы не было висячих горутин, так что это не страшно.

Рекомендую посмотреть занятие с разбором ДЗ. Там разбирается эта проблема и смежная с ней.

2021-09-13 14:08 UTC, dmitriye commented on hw06_pipeline_execution/pipeline.go
> +				out <- v
Добавил дрейн

2021-09-13 14:21 UTC, dmitriye commented on hw06_pipeline_execution/pipeline.go
> +	return out
@kulti кажется понял. Так происходит из-за того, что нет приоритизации чтения из done канала в цикле? при первом done селект может выбрать не чтение из done, а чтение из in и пойдет в след done

2021-09-13 14:22 UTC, dmitriye commented
> Дмитрий, хорошее решение и тесты 👍
> 
> Есть один недочет в цепочке стейджей. Из-за него может нестабильно работать.

Спасибо за проверку и комментарии. Недочёты исправил и обновил репозиторий.

2021-09-19 06:04 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +	return out
Нет. Посмотрите какую цепочку стейджей я написал. Кажется, я ошибся и все в порядке. Цепочка такая:
in -> done -> stage_1 -> done -> ... -> stage_n -> done -> out

Если бы была такая, как я написал при первом прочтении, то наружу отдавался бы канал out от последнего стейджа. А время его закрытия непрогнозируемо долгое, т.к. в стейдже все, что угодно может происходить.

2021-09-19 06:05 UTC, kulti approved these changes
Дмитрий, спасибо за правки.

Похоже, я ошибся при первом ревью. Все в порядке с решением. ДЗ принято — 10/10.

2021-09-19 14:25 UTC, merged